apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpolicies.myorg.io
spec:
  group: myorg.io
  scope: Cluster
  names:
    plural: clusterpolicies
    singular: clusterpolicy
    kind: ClusterPolicy
    shortNames:
      - cpol
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                  description: Human-readable description of the policy
                enforcement:
                  type: string
                  enum: ["audit", "enforce"]
                  description: Whether to just audit or actively enforce the policy
                rules:
                  type: array
                  description: List of rules in this policy
                  items:
                    type: object
                    properties:
                      resource:
                        type: string
                        description: Target resource (e.g., pods, deployments)
                      constraint:
                        type: string
                        description: Constraint applied (e.g., must have label `team`)
              required: ["enforcement", "rules"]
            status:
              type: object
              properties:
                violations:
                  type: integer
                  description: Number of current violations
---
apiVersion: myorg.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: require-team-label
spec:
  description: "All pods must have a team label"
  enforcement: enforce
  rules:
    - resource: pods
      constraint: "mustHaveLabel: team"
