apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.myorg.io
spec:
  group: myorg.io
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
    shortNames:
      - acfg
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  description: Number of application replicas
                image:
                  type: string
                  description: Container image for the app
                env:
                  type: array
                  description: Environment variables
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
              required: ["image"]
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                  description: Number of replicas currently available