apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databaseconfigs.myorg.io
spec:
  group: myorg.io
  scope: Namespaced
  names:
    plural: databaseconfigs
    singular: databaseconfig
    kind: DatabaseConfig
    shortNames:
      - dbcfg
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                engine:
                  type: string
                  enum: ["postgres", "mysql", "mongodb"]
                  description: Database engine type
                version:
                  type: string
                  description: Database version
                storage:
                  type: string
                  pattern: "^[0-9]+Gi$"
                  description: Storage size (e.g., 20Gi)
                users:
                  type: array
                  description: List of database users
                  items:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
              required: ["engine", "version", "storage"]
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: Current state of the database (Pending, Running, Failed)
